name = "backend"
compatibility_date = "2024-04-17"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZGQyYjhjZDItYzIyMy00OTI3LTgyM2MtMGQ4ZGNhNmRlYWM0IiwidGVuYW50X2lkIjoiNWE2YTE0NTExZjFlYTQyOWJmZjI1Nzg3YWRlYmE3NTQ3OTc2MmQwY2Q1NDJiMTMwMjBmZDkzOGFhNTIwZWMyMCIsImludGVybmFsX3NlY3JldCI6IjA5MTBhOGJhLTQxNDQtNDM2NC1iYWNmLTIzMjZmMzFhYTAzYiJ9.zYC1bsYmq5TpMdRLOoprnRdRrCCUVu0Ph520xddLeeo"

